<?php

namespace App\Models\Home;

use App\Models\Common\Buttons;
use App\Models\Common\Images;
use App\Models\Common\Languages;
use App\Trade\LanguageCheckTrade;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MainBanner extends Model
{ // establish relationship
    //button
    //image 1920 - 970

    protected $fillable = [
        "title^ru",
        "title^uz",
        "title^en",
        "mini_header^ru",
        "mini_header^uz",
        "mini_header^en",
    ];

    public $timestamps = false;
    use HasFactory, LanguageCheckTrade;

    public function button()
    {
        return $this->morphOne(Buttons::class, "button");
    }

    public function image()
    {
        return $this->morphOne(Images::class, "image");
    }

    public function __get($key)
    {
        if ($this->checkItIsTranslatable($key)) {
            return $this[$this->translate($key)];
        }
        return parent::__get($key); // TODO: Change the autogenerated stub
    }
}
