<?php

namespace App\Models\CustomModel;

use App\TraitDirectory\LanguageCheckTrade;
use Illuminate\Database\Eloquent\Model;

class ModelWithTranslate extends Model
{
    use LanguageCheckTrade;

    public function __get($key)
    {
        if ($this->checkItIsTranslatable($key)) {
            return $this[$this->translate($key)];
        }
        return parent::__get($key); // TODO: Change the autogenerated stub
    }
}
